In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
a = np.arange(1,101)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [32]:
b = np.arange(501,601)

In [33]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [34]:
train_test_split(a)

[array([ 38,  36,  78,  68,  15,  51,  99,  66,  87,  72,  74,  55,  98,
         56,  90,  40,  63,   4,  79,  62,  12,  11,  70,  69,  31,  21,
         33,   9,  30,  73,  95,  22,  39,  58,  35,  32,  10,  97,  80,
         28,  60,  53,  61,  77,  34,  29,  45,  71, 100,  89,  76,  17,
         43,   6,  94,  46,  42,  20,  18,  41,  59,  85,  19,  13,  82,
         27,  50,   1,  16,  47,  91,  37,  25,  64,  83]),
 array([75, 23, 65, 52,  8, 14, 26, 48,  3, 24, 96, 86, 49, 92, 67, 54, 81,
        88, 57, 93,  2, 44, 84,  5,  7])]

In [35]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.2, random_state=69)

In [36]:
a_train.shape,a_test.shape

((80,), (20,))

In [37]:
a_train

array([ 37,  29,   6,  41,  59,  79,   7,  72,  16,  88,  26,  35,   2,
        70,  77,  53,  52,  92,   5,   8,  33,  47,  28,  58,  42,  64,
         1,  66, 100,  78,  75,  87,  19,  69,  67,  12,  51,  20,  61,
        60,  43,  30,  17,  46,  49,  62,  68,  71,  94,  22,  15,  44,
        36,  24,  45,  86,  48,  83,  82,   3,  25,  40,  81,   4,  54,
        99,  38,  13,  89,  39,  57,  10,  23,  50,  21,  56,  91,  74,
        76,  55])

In [38]:
a_test

array([73, 32, 14, 84, 34,  9, 27, 90, 65, 98, 95, 85, 11, 18, 96, 80, 31,
       63, 93, 97])

In [39]:
b_train.shape, b_test.shape

((80,), (20,))

In [40]:
b_train

array([537, 529, 506, 541, 559, 579, 507, 572, 516, 588, 526, 535, 502,
       570, 577, 553, 552, 592, 505, 508, 533, 547, 528, 558, 542, 564,
       501, 566, 600, 578, 575, 587, 519, 569, 567, 512, 551, 520, 561,
       560, 543, 530, 517, 546, 549, 562, 568, 571, 594, 522, 515, 544,
       536, 524, 545, 586, 548, 583, 582, 503, 525, 540, 581, 504, 554,
       599, 538, 513, 589, 539, 557, 510, 523, 550, 521, 556, 591, 574,
       576, 555])

In [41]:
b_test

array([573, 532, 514, 584, 534, 509, 527, 590, 565, 598, 595, 585, 511,
       518, 596, 580, 531, 563, 593, 597])